apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-deployment
  labels:
    app: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader
        image: simonliska/saturday:go-rabbit-latest
        imagePullPolicy: Always
        command: ["./read"]