apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: sender
        image: simonliska/saturday:go-rabbit-latest
        imagePullPolicy: Always
        command: ["./send"]